---
title: "Training Overview"
output: 
  html_document:
    theme: flatly
    toc: true
    toc_depth: 4
    toc_float: true
    css: tutorial_style.css
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tutorials

These tutorials instruct on a workflow for collecting and managing geospatial data in the field using open-source tools QGIS and QField. 

This training will cover the following:

### [Lesson 1](lesson_1.html)

1. QGIS and QField setup 
2. Project creation and form generation

### [Lesson 2](lesson_2.html)

3. Opening projects in QField
4. Data collection using QField
5. Syncing data from mobile devices

### [Lesson 3](lesson_3.html)

6. Generating complex data collection forms

### [Lesson 4](lesson_4.html)

7. Managing QGIS data collection projects on remote devices
8. Syncing data collected on multiple devices with a central dataset

<br>

## Use Cases

### [Ground truth data collection](usecase_groundtruth.html)

Use QField to collect ground truth points for validating land cover maps generated from satellite images.

### [Community mapping](usecase_communitymap.html)

Use QField to map landscape features used to support livelihoods.

### [Ground Truth - ERPD Pilot](usecase_erpdpilot.html)

Second tutorial, using QField to collect ground truth points for validating land cover maps generated from satellite images.

### [Tonga Crop Survey](tonga_crop_survey_1.html)

Slide deck demonstrating how QField can be used for farm and crop surveys.

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>
<footer>
<p>
<hr>
<div style="text-align: center;">
*The ACIAR-Livelihoods and Landscapes team (tutorial creators) acknowledge the developers of the open source software QGIS and [QField](https://qfield.org).*</div>
</p>
</footer>
